baskervilleweb/archive/urls.py
from django.conf.urls import include, url
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

from . import models,views

app_name="archive"

urlpatterns = [
    url( 
        r'^$',
        TemplateView.as_view(template_name="archive/index.html"),
        name="index" 
    ),

    ## photos

    url( r'^photo/?$',views.PhotoListView.as_view(),name="photo_list" ),
    url( r'^photo/(?P<pk>\d+)/?$',
         DetailView.as_view(model=models.PhotoAsset),
         name="photo_detail" ),
    url( r'^photo/(?P<pk>\d+)\.thumb\.jpeg/?$',
         views.PhotoThumbView.as_view(),name="photo_thumb" ),
    url( r'^photo/(?P<pk>\d+)\.(?P<ext>[^.]*)/?$',
         views.PhotoImageView.as_view(model=models.PhotoAsset),
         name="photo_image" ),

    ## documents

    url( r'^document_asset/(?P<pk>\d+)\.thumb\.jpeg/?$',
         views.DocumentAssetThumbView.as_view(),
         name="document_asset_thumb" ),
    url( r'document/by_label/(?P<slug>\w+)/?$',
         DetailView.as_view(model=models.Document,slug_field="label"),
         name="document_detail_by_label"),
    url( r'document/(?P<pk>\d+)/?$',
         DetailView.as_view(model=models.Document),
         name="document_detail"),
    

]

baskervilleweb/bibliography/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

from . import models,views

app_name="bibliography"

urlpatterns = [
    url( r'^$',TemplateView.as_view(template_name="bibliography/index.html"),name="index" ),
    url( r'^catalog/?$',views.CatalogView.as_view(),name="catalog"),
    url( r'^categories/?$',
         ListView.as_view(model=models.CategoryTreeNode,
                          queryset=models.CategoryTreeNode.objects.filter(level=0),
                          context_object_name="categorytreenode_list"),
         name="categories"),
    
    # url( r'^categories/graph/(?P<pk>\d+)/?$',views.CategoryGraphView.as_view()),
    # url( r'^categories/graph/?$',views.CategoryGraphView.as_view()),
    
    # url( r'^categories/graph2/(?P<pk>\d+)/?$',views.CategoryGraphView.as_view(template_name="bibliography/provad3.html")),
    # url( r'^categories/graph2/?$',views.CategoryGraphView.as_view(template_name="bibliography/provad3.html")),
    
    #url( r'^categories/graph/?$',ListView.as_view(model=CategoryTreeNode,
    #                                           template_name="bibliography/categorytreenode_graph.html",
    #                                           queryset=CategoryTreeNode.objects.filter(level=0),
    #                                           context_object_name="categorytreenode_list")),
    
    url( r'^categories/categorizer/(?P<pk>\d+)/?$',views.CategoryChildrenView.as_view(), name="categories-categorizer-branch"),
    
    url( r'^categories/categorizer/?$',views.CategoryChildrenView.as_view(),name="categories-categorizer"),
    url( r'^books/categorizer/',
         ListView.as_view(model=models.Book,
                          paginate_by=100,
                          context_object_name="book_list",
                          template_name="bibliography/book_categorizer.html"),
         name="books-categorizer"),
    
    url( r'^insert/',views.BooksInsertView.as_view(),name="insert"),
    url( r'^author/create/?$',views.AuthorCreateView.as_view(),name="author-create"),
    url( r'^author/search/?$',views.AuthorSearchView.as_view(),name="author-search"),
    url( r'^author/insert/?$',views.AuthorInsertView.as_view(),name="author-insert"),
    url( r'^author/(?P<pk>\d+)/?$',DetailView.as_view(model=models.Author),name="author-detail"),
    url( r'^author/?$',ListView.as_view(
        model=models.Author,
        context_object_name="author_list",
        paginate_by=50),name="author-list"),
    url( r'^book/create/?$',views.BookCreateView.as_view(),name="book-create"),
    url( r'^book/(?P<pk>\d+)/?$',DetailView.as_view(model=models.Book),name="book-detail"),

    url( r'^publisher/create/?$',views.PublisherCreateView.as_view(),name="publisher-create"),
    url( r'^publisher/(?P<pk>\d+)/?$',DetailView.as_view(model=models.Publisher),name="publisher-detail"),
    url( r'^publisher/?$',ListView.as_view(model=models.Publisher),name="publisher-list"),

    url( r'^publisherisbn/?$',ListView.as_view(model=models.PublisherIsbn),name="publisherisbn-list"),
    url( r'^publisherisbn/alpha/?$',
         ListView.as_view(model=models.PublisherIsbn,queryset=models.PublisherIsbn.objects.isbn_alpha()),
         name="publisherisbn-alpha"),

    url( r'^books/seriewithoutisbn/?$',
         ListView.as_view(model=models.BookSerieWithoutIsbn),name="book-serie-without-isbn"),

    url( r'^books/alpha/?$',
         ListView.as_view(model=models.Book,queryset=models.Book.objects.isbn_alpha()),
         name="book-list-alpha"),
    url( r'^books/byisbnpub/(?P<isbn>.+?)/?$',
         views.BookByIsbnPubListView.as_view(),
         name="book-by-isbn-pub"),

    url( r'^publications/?$',
         ListView.as_view(model=models.Publication),
         name="publication-list"),
    url( r'^publications/alpha/?$',
         ListView.as_view(model=models.Publication,queryset=models.Publication.objects.issn_alpha()),
         name="publication-list-alpha"),
    url( r'^publication/(?P<pk>\d+)/?$',
         views.PublicationDetailView.as_view(),
         name="publication-detail"),
    url( r'^publication/(?P<pk>\d+)/add_author/?$',
         views.PublicationIssuesAuthorAddView.as_view(),
         name="publication-issues-author-add"),
    url( r'^publication/(?P<pk>\d+)/choice_author/?$',
         views.PublicationIssuesAuthorChoiceView.as_view(),
         name="publication-issues-author-choice"),
    url( r'^publication/(?P<pk>\d+)/create_author/?$',
         views.PublicationIssuesAuthorCreateView.as_view(),
         name="publication-issues-author-create"),
    url( r'^publication/(?P<pk>\d+)/search_author/?$',
         views.PublicationIssuesAuthorSearchView.as_view(),
         name="publication-issues-author-search"),

    url( r'^nameformatcollection/?$',
         ListView.as_view(model=models.NameFormatCollection),
         name="nameformatcollection-list"),

    # url( r'^json/categories/treenode/(?P<label_children>.+?)/(?P<level>\d+)/?$',views.JsonTreeView.as_view()),
    # url( r'^json/categories/nodeslinks/(?P<pk>\d+)/?$',views.JsonCategoryNodesLinksView.as_view()),
    # url( r'^json/categories/nodeslinks/?$',views.JsonCategoryNodesLinksView.as_view()),
    # url( r'^json/categories/nodeslinks2/(?P<pk>\d+)/?$',
    #   views.JsonCategoryNodesLinksView2.as_view()),
    # url( r'^json/categories/nodeslinks2/?$',
    #   views.JsonCategoryNodesLinksView2.as_view()),
    url( r'^json/publisher/create/?$',views.JsonPublisherCreateView.as_view(),name="json-publisher-create"),
    url( r'^json/publisher/(?P<pk>\d+)/?$',views.JsonDetailView.as_view(model=models.Publisher),name="json-publisher-detail"),
    url( r'^json/author/create/',views.JsonAuthorCreateView.as_view(),name="json-author-create"),
    url( r'^json/author/(?P<pk>\d+)/?$',views.JsonDetailView.as_view(model=models.Author),name="json-author-detail"),
    url( r'^json/book/create/?$',views.JsonBookCreateView.as_view(),name="json-book-create"),
    url( r'^json/book/(?P<pk>\d+)/?$',views.JsonDetailView.as_view(model=models.Book),name="json-book-detail"),
    url( r'^json/book/(?P<pk>\d+)/change_categories/?$',views.JsonBookChangeCategoriesView.as_view(),
         name="json-book-change-categories"),
    url( r'^json/category/(?P<pk>\d+)/change_parents/?$',views.JsonCategoryChangeParentsView.as_view(),
         name="json-category-change-parents"),
]

baskervilleweb/home/urls.py
from django.conf.urls import include, url
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

app_name="home"

urlpatterns = [
    url( r'^$',TemplateView.as_view(template_name="home/index.html"),name="home_index" ),
]

baskervilleweb/recipebook/urls.py
from django.conf.urls import include, url
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

app_name="recipebook"

from . import models

urlpatterns = [
    url( r'^$',ListView.as_view(model=models.RecipeCategory),name="index" ),
    url( r'^recipe/$',ListView.as_view(model=models.RecipeCategory),name="recipecategory_list" ),
    url( r'^recipe/(?P<pk>\d+)/?$',DetailView.as_view(model=models.Recipe),name="recipe_detail" ),
]

baskervilleweb/warehouse/urls.py
from django.conf.urls import include, url
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

from . import models,views

app_name="warehouse"

urlpatterns = [
    # url( r'^$',views.PhotoListView.as_view(),name="index" ),
    url( r'^$',views.IndexView.as_view(),name="index" ),
    url( r'^container/?$',ListView.as_view(model=models.Container),name="container_list" ),
    url( r'^container/(?P<pk>\d+)/?$',
         DetailView.as_view(model=models.Container),
         name="container_detail" ),
    url( r'^container/by_label/(?P<slug>\w+)/?$',
         DetailView.as_view(model=models.Container,slug_field="label"),
         name="container_detail_by_label" ),

    # url( r'^photo/(?P<pk>\d+)/?$',DetailView.as_view(model=models.Photo),name="photo_detail" ),
    # url( r'^photo/(?P<pk>\d+)\.thumb\.jpeg/?$',
    #      views.PhotoThumbView.as_view(),name="photo_thumb" ),
    # url( r'^photo/(?P<pk>\d+)\.(?P<ext>[^.]*)/?$',
    #      views.PhotoImageView.as_view(model=models.Photo),name="photo_image" ),
    # url( r'^document_asset/(?P<pk>\d+)\.thumb\.jpeg/?$',
    #      views.DocumentAssetThumbView.as_view(),name="document_asset_thumb" ),
]

baskervilleweb/templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" 
      {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

<title>Baskerville{% block title %}{% endblock %}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<link rel="icon" href='{% static "images/logo-baskerville-piccolo.png" %}' 
      type="image/png"/>

<!--
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" 
      rel="stylesheet"/> 
-->

<!-- <script src="https://kit.fontawesome.com/398c6b2bdc.js"></script>-->


<!-- <link rel="stylesheet" type="text/css" 
      href='https://code.jquery.com/ui/1.12.1/themes/sunny/jquery-ui.css'/> -->

<link rel="stylesheet" type="text/css" href='{% static "others/jquery-ui.css" %}'/>
<link rel="stylesheet" type="text/css" href='{% static "others/fontawesome-free-5.15.1-web/css/all.css" %}'/>

<link rel="stylesheet" type="text/css" href='{% static "css/baskerville.css" %}'/>

</head>

<body>

<!-- 
     ----------------------------
     DOM
     ----------------------------
-->

<header>
  <div class="title">
    <a href="{% url 'home' %}">
      <img src="{% static "images/logo-baskerville.png" %}" alt="home"/>
    </a>
    <h1>Baskerville</h1>
  </div>

  <nav>
    <section id="sitemenu">
      <button id="sitemenu-open" data-target="#sitemenu" 
	      class="menu-opener" aria-label="site menu">
	<i class="fas fa-bars"></i>
      </button>

      <h2 class="hidden">{% trans "View menu" %}</h2>

      <a href="/">
	<i class="fa fa-home"></i> 
	{% trans "Home" %}
      </a>

      <a href="{% url "bibliography:index" %}">
	<i class="fa fa-university"></i> 
	{% trans "Library" %}
      </a>

      <a href="{% url "archive:index" %}">
	<i class="fa fa-archive"></i> 
	{% trans "Archive" %}
      </a>

      <a href="{% url "recipebook:index" %}">
	<i class="fa fa-book"></i> 
	{% trans "Recipe Book" %}
      </a>

      <a href="{% url "warehouse:index" %}">
	<i class="fa fa-warehouse"></i> 
	{% trans "Warehouse" %}
      </a>

    </section>
    
    <section id="usermenu">
      <button id="usermenu-open" data-target="#usermenu" 
	      class="menu-opener"  aria-label="site menu">
	<i class="fas fa-user"></i>
      </button>
      <h2 class="hidden">{% trans "User navigation" %}</h2>
      {% include "baskervilleauth/includes/user_links.html" %}
    </section>
    
  </nav>
  
</header>

<main>
  {% block content %}{% endblock %}
</main>

<!-- 
     ----------------------------
     javascript 
     ----------------------------
-->
  

<script type="text/javascript" src='{% static "others/jquery-3.5.1.min.js" %}'></script> 
<script type="text/javascript" src='{% static "others/jquery-ui.min.js" %}'></script>
<script type="text/javascript" src='{% static "others/luxon.min.js" %}'></script>
<script type="text/javascript" src='{% static "others/d3.v5.min.js" %}'></script>
<script type="text/javascript" src='{% static "js/jquery-ui-santaclara-widgets.js" %}'></script>

{% block script %}
<script type="text/javascript" src='{% static "js/default.min.js" %}'></script>
{% endblock script %}

</body>
</html>