baskervilleweb/home/urls.py
from django.conf.urls import include, url
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

app_name="home"

urlpatterns = [
    url( r'^$',TemplateView.as_view(template_name="home/index.html"),name="home_index" ),
]

baskervilleweb/recipebook/urls.py
from django.conf.urls import include, url
from django.views.generic import DetailView,ListView,UpdateView,CreateView
from django.views.generic import TemplateView,ListView

app_name="recipebook"

from . import models

urlpatterns = [
    url( r'^$',ListView.as_view(model=models.RecipeCategory),name="index" ),
    url( r'^recipe/$',ListView.as_view(model=models.RecipeCategory),name="recipecategory_list" ),
    url( r'^recipe/(?P<pk>\d+)/?$',DetailView.as_view(model=models.Recipe),name="recipe_detail" ),
]

baskervilleweb/recipebook/models.py
from django.db import models
from django.core import validators
from django.utils.functional import cached_property

import re

# Create your models here.

class NameAbstractManager(models.Manager):
    def deserialize(self,ser):
        obj,created=self.get_or_create(name=ser)
        return obj
        

class NameAbstract(models.Model):
    name = models.CharField(max_length=4096,unique=True)

    objects=NameAbstractManager()

    class Meta:
        abstract = True
        ordering = [ 'name' ]

    def __str__(self): 
        return self.name

    def __serialize__(self): return self.name

class Tool(NameAbstract): pass
class FoodCategory(NameAbstract): pass
class RecipeCategory(NameAbstract): pass

class StepSequenceManager(NameAbstractManager):
    def deserialize(self,ser):
        obj,created=self.get_or_create(name=ser["name"])
        for step in ser["steps"]:
            Step.objects.deserialize(obj,step)
        return obj

class StepSequence(NameAbstract):
    #parent = models.ForeignKey('self',on_delete=models.SET_NULL,blank=True,null=True)

    #class Meta:
    #    ordering = [ 'name' ]

    objects=StepSequenceManager()

    def tools(self):
        tools={}
        for step in self.step_set.all():
            for rel in step.steptoolrelation_set.all():
                if not rel.tool.name in tools: tools[rel.tool.name]=0
                if tools[rel.tool.name]==0: 
                    tools[rel.tool.name]=1
                    continue
                if rel.use_new:
                    tools[rel.tool.name]+=1
        return tools.items()

    def steps(self):
        steps=[]
        for step in self.step_set.all():
            steps.append(step)
        return steps

    def __serialize__(self):
        return {
            "name": self.name,
            "steps": [ s.__serialize__() for s in self.step_set.all() ]
        }

class StepManager(models.Manager):
    def deserialize(self,sequence,ser):
        obj,created=self.update_or_create(
            sequence=sequence,
            pos=ser["pos"],
            defaults={
                "description": ser["description"]
            }
        )
        for tool_name,use_new in ser["tools"]:
            tool=Tool.objects.deserialize(tool_name)
            StepToolRelation.objects.update_or_create(
                step=obj,
                tool=tool,
                defaults={
                    "use_new": use_new
                }
            )
        return obj

class Step(models.Model):
    description = models.CharField(max_length=8192)
    sequence = models.ForeignKey(StepSequence,on_delete=models.PROTECT)
    pos = models.PositiveIntegerField()
    #tools = models.ManyToManyField(Tool,blank=True,through='StepToolRelation')

    objects=StepManager()

    class Meta:
        ordering = [ "sequence","pos" ]
        unique_together = [ "sequence","pos" ]

    def __str__(self): return self.description

    def __serialize__(self):
        return {
            "description": self.description,
            "pos": self.pos,
            "tools":[ (rel.tool.__serialize__(),
                       rel.use_new) for rel in self.steptoolrelation_set.all() ]
        }

class StepToolRelation(models.Model):
    tool = models.ForeignKey(Tool,on_delete=models.PROTECT)
    step = models.ForeignKey(Step,on_delete=models.PROTECT)
    use_new = models.BooleanField(default=False)

    def __str__(self):
        return "%s/%s" % (self.tool,self.step)

###

class RecipeManager(NameAbstractManager):
    def deserialize(self,ser):
        defaults={
            "serving": ser["serving"],
            "execution": StepSequence.objects.get(name=ser["execution"]),
            "category": RecipeCategory.objects.get(name=ser["category"]),
        }

        obj,created=self.update_or_create(name=ser["name"],defaults=defaults)

        for g_ser,factor in ser["ingredient_groups"]:
            grp=IngredientGroup.objects.get(name=g_ser)
            RecipeIngredientGroupRelation.objects.update_or_create(
                group=grp,
                recipe=obj,
                defaults={"factor": factor}
            )

        for a_ser,factor in ser["ingredient_alternatives"]:
            alt=IngredientAlternative.objects.get(name=a_ser)
            RecipeIngredientAlternativeRelation.objects.update_or_create(
                alternative=alt,
                recipe=obj,
                defaults={"factor": factor}
            )

        return obj

class Cell(object):
    def __init__(self,val,td="td",colspan=1,rowspan=1,style=""):
        self.td=td
        self.val=val
        self.colspan=colspan
        self.rowspan=rowspan
        self.style=style

class Table(object):

    def __init__(self,num_cols):
        self._num_cols=num_cols
        self.data=[]

    def add_title(self,name,level=0):
        row=[]
        if level==0:
            row.append( Cell(name,td="th",style="title",colspan=self._num_cols) )
            self.data.append(row)
            return
        row.append( Cell("",style="empty") )
        row.append( Cell(name,td="th",style="sub",colspan=self._num_cols-1) )
        self.data.append(row)

    def _data_cell(self,d,**kwargs):
        if type(d) is str:
            return Cell(d,**kwargs)
        kwargs=kwargs.copy()
        if "style" in kwargs:
            kwargs["style"]+=" "+d[1]
        else:
            kwargs["style"]=d[1]
        return Cell(d[0],**kwargs)

    def add_row(self,data,level=0):
        row=[]
        num_data=len(data)
        if level>0:
            row.append( Cell("",style="empty",colspan=level) )
        row.append( self._data_cell(data[0],style="datafirst",
                                    colspan=self._num_cols-level-len(data)) )
        for d in data[1:]:
            row.append( self._data_cell(d,style="data") )
        self.data.append(row)
            

class Recipe(NameAbstract):
    category = models.ForeignKey(RecipeCategory,on_delete=models.PROTECT)
    serving = models.PositiveIntegerField(blank=True,default=4,
                                          validators=[validators.MinValueValidator(1)])
    execution = models.ForeignKey(StepSequence,on_delete=models.PROTECT)

    objects=RecipeManager()

    def __serialize__(self):
        return {
            "name": self.name,
            "category": self.category.name,
            "execution": self.execution.name,
            "serving": self.serving,
            "ingredient_groups": [ 
                (rel.group.name,
                 rel.factor) for rel in self.recipeingredientgrouprelation_set.all() ],
            "ingredient_alternatives": [ 
                (rel.alternative.name,
                 rel.factor) for rel in self.recipeingredientalternativerelation_set.all() ],
            
        }
        
    def _ingredient_row_data(self,factor,ingredient):
        name=ingredient.food.name
        if ingredient.preparation is not None:
            preparation=ingredient.preparation.name
        else:
            preparation=""
        if ingredient.measure.base=="qb":
            return ("q.b.","right"),name,preparation,"",""

        quantity="%2.3f" % (factor*ingredient.quantity)
        quantity=quantity.strip("0").rstrip(".")
        quantity_base=str(int(round(factor*ingredient.quantity_base)))

        return ( 
            (quantity,"right"),ingredient.measure.abbreviation,
            name,preparation,
            (quantity_base,"right light"),(ingredient.measure.base,"light"),
        )

    class IngredientWrapper(object):
        def __init__(self,factor,ingredient):
            self._factor=factor
            self._ingredient=ingredient

        def __getattribute__(self,name):
            if name not in [ "_factor","_ingredient","quantity", "quantity_base", "quantity_str", "quantity_base_str" ]:
                return self._ingredient.__getattribute__(name)
            if name in [ "_factor","_ingredient" ]:
                return object.__getattribute__(self,name)
            if name=="quantity":
                return self._factor*self._ingredient.quantity
            if name=="quantity_base":
                return self._factor*self._ingredient.quantity_base
            if name=="quantity_base_str":
                return str(int(round(self._factor*self._ingredient.quantity_base)))
            quantity="%2.3f" % (self._factor*self._ingredient.quantity)
            quantity=quantity.strip("0").rstrip(".")
            return quantity
            

    def ingredient_groups(self):
        groups={}
        for g_rel in self.recipeingredientgrouprelation_set.all():
            groups[g_rel.group.name]=[]
            for i_rel in g_rel.group.ingredientingredientgrouprelation_set.all():
                factor=g_rel.factor*i_rel.factor
                groups[g_rel.group.name].append(self.IngredientWrapper(factor,i_rel.ingredient))
        return groups.items()
                            
    def ingredient_alternatives(self):
        alternatives={}
        for a_rel in self.recipeingredientalternativerelation_set.all():
            groups={}
            for g_rel in a_rel.alternative.ingredientalternativegrouprelation_set.all():
                groups[g_rel.group.name]=[]
                for i_rel in g_rel.group.ingredientingredientgrouprelation_set.all():
                    factor=a_rel.factor*g_rel.factor*i_rel.factor
                    groups[g_rel.group.name].append(self.IngredientWrapper(factor,i_rel.ingredient))
            alternatives[a_rel.alternative.name]=groups.items()
        return alternatives.items()
        

    def ingredients_table(self):
        tab=Table(8)

        for g_rel in self.recipeingredientgrouprelation_set.all():
            tab.add_title(g_rel.group.name)
            for i_rel in g_rel.group.ingredientingredientgrouprelation_set.all():
                factor=g_rel.factor*i_rel.factor
                data=self._ingredient_row_data(factor,i_rel.ingredient)
                tab.add_row(data,level=1)

baskervilleweb/recipebook/templates/recipebook/recipe_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1>{{ recipe }}</h1>

<article class="recipebook">

  <aside>

    <section>
    <h2>{% trans "Ingredients" %}</h2>

    <table class="ingredients">

      {% for gname,ilist in recipe.ingredient_groups %}
      {% with groupid="group-"|add:forloop.counter %}
      <tbody id="{{ groupid }}">
      <tr><th colspan="8" class="title">{{ gname }}</th></tr>
      {% for ingr in ilist %}
      {% include "recipebook/includes/ingredient.html" with ingrid=groupid|add:"-ingr-"|add:forloop.counter ingredient=ingr only %}
      {% endfor %}
      </tbody>
      {% endwith %}
      {% endfor %}

      {% for aname,glist in recipe.ingredient_alternatives %}
      {% with alternativeid="alt-"|add:forloop.counter %}
      <tbody id="{{ alternativeid }}"><tr><th colspan="8" class="title">{{ aname }} <span class="selectedgroup"></span></th></tr></tbody>
      {% for gname,ilist in glist %}
      {% with groupid=alternativeid|add:"-group-"|add:forloop.counter %}
      <tbody id="{{ groupid }}" data-alternative="#{{ alternativeid }}">
	<tr class="grouprow">
	  <td class="empty">&nbsp;</td>
	  <th colspan="7" class="sub">
	    <input type="checkbox" class="selectalternative" data-group="#{{ groupid }}" data-alternative="#{{ alternativeid }}">
	    alt. {{ forloop.counter }}: <span class="groupname">{{ gname }}</span>
	  </th>
	</tr>
	{% for ingr in ilist %}
	<tr class="ingredientrow" id="ingredient{{ ingr.id }}">
	  <td class="empty" colspan="2">&nbsp;</td>
	  {% if ingr.measure.base == "qb" %}
	  <td class="empty"></td>
	  <td class="datafirst">q. b.</td>
	  <td class="data">{% if ingr.preparation %}<i class="fas fa-caret-right"></i>{% endif %} {{ ingr.food.name }}</td>
	  <td class="data">{% if ingr.preparation %}{{ ingr.preparation }}{% endif %}</td>
	  <td class="data right light"></td>
	  <td class="data"></td>
	  {% else %}
	  <td class="datafirst right">{{ ingr.quantity_str }}</td>
	  <td class="data">{{ ingr.measure.abbreviation }}</td>
	  <td class="data">{% if ingr.preparation %}<i class="fas fa-caret-right"></i>{% endif %} {{ ingr.food.name }}</td>
	  <td class="data">{% if ingr.preparation %}{{ ingr.preparation }}{% endif %}</td>
	  <td class="data right light">{{ ingr.quantity_base_str }}</td>
	  <td class="data light">{{ ingr.measure.base }}</td>
	  {% endif %}
	</tr>
	{% if ingr.preparation %}
	<tr>
	  <td class="empty" colspan="4">&nbsp;</td>
	  <td colspan="4">
	    <ol>
	      {% for step in ingr.preparation.steps %}
	      <li>{{ step }}</li>
	      {% endfor %}
	    </ol>
	  </td>
	</tr>
	{% endif %}
	{% endfor %}
      </tbody>


      {% endwith %}
      {% endfor %}
      {% endwith %}
      {% endfor %}

    </table>

    </section>

    <section>
      <h2>{% trans "Tools" %}</h2>

      <table>
	{% for tool,num in recipe.tools %}
	<tr>
	  <td>{{ tool }}:</td>
	  <td>{{ num }}</td>
	</tr>
	{% endfor %}
      </table>
    </section>

  </aside>

  <section>

    <section>
      <h1>{% trans "Ingredients preparation" %}</h1>
      
      <ol>
	{% for ing in recipe.ingredient_set.all %}
	{% for step in ing.format_preparation %}
	<li>{{ step }}</li>
	
	{% endfor %}
	{% endfor %}
      </ol>
    </section>
    
    <section>
      <h1>{% trans "Execution" %}</h1>
      
      <ol>
	{% for step in recipe.execution.steps %}
	<li>{{ step }}</li>
	
	{% endfor %}
      </ol>
      
    </section>
  </section>


</article>

{% endblock content %}

baskervilleweb/recipebook/templates/recipebook/recipecategory_list.html
{% extends "base.html" %}

{% block content %}

<div class="recipebook">
{% for cat in object_list %}
<section>
<h1>{{ cat }}</h1>
{% for recipe in cat.recipe_set.all %}
<a href="{% url 'recipebook:recipe_detail' recipe.id %}">{{ recipe }}</a>

{% endfor %}
</section>
{% endfor %}
</div>

{% endblock content %}